version: '3.9'
services:
  patientdb:
    container_name: patientdb
    image: mariadb
    build: mariadb
    volumes:
      - ./mariadb/patient.sql:/docker-entrypoint-initdb.d/patient.sql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=mediscreen
    ports:
      - 3306:3306
    healthcheck:
      #test: ["CMD", "mysqlcheck", "-c", "-h", "localhost", "-P", "3306", "-B", "mediscreen", "-u", "admin", "-p", "admin"]
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      retries: 20
    
  mongodb:
    container_name: note-database
    build: mongodb    
    volumes: 
      - ./mongodb/data/db/:/data/db/
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: patient 
    ports:
      - 27017:27017

  service-patient:
    depends_on:
      - patientdb
    container_name: service-patient
    build: service-patient
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://patientdb:3306/mediscreen
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    
    
  service-note: 
    container_name: service-note
    build: service-note
    ports: 
      - 8082:8082
    links:
      - mongodb